"""
Resume Score Schemas

Purpose:
Defines the validated data contracts for the Resume
Intelligence scoring pipeline.

Architecture:

GeminiScoreEvaluation
    ↓
Gemini-facing structured-output contract

ResumeScore
    ↓
Application-facing validated contract

The Gemini-facing schema is intentionally kept simple
for compatibility with Gemini Structured Output.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


# =========================================================
# Gemini Response Models
# =========================================================
#
# These models are passed directly to Gemini through
# response_schema.
#
# Keep these models simple and Gemini-compatible.
# =========================================================


class GeminiScoreStrength(BaseModel):
    """
    Strength returned by Gemini.
    """

    category: str = Field(
        ...,
        min_length=1,
        description=(
            "Category associated with the identified "
            "strength."
        ),
    )

    title: str = Field(
        ...,
        min_length=1,
        description=(
            "Short title describing the strength."
        ),
    )

    description: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation of the strength."
        ),
    )


class GeminiScoreImprovement(BaseModel):
    """
    Improvement recommendation returned by Gemini.
    """

    category: str = Field(
        ...,
        min_length=1,
        description=(
            "Category associated with the improvement."
        ),
    )

    title: str = Field(
        ...,
        min_length=1,
        description=(
            "Short title describing the improvement."
        ),
    )

    description: str = Field(
        ...,
        min_length=1,
        description=(
            "Specific actionable improvement."
        ),
    )

    priority: int = Field(
        ...,
        ge=1,
        le=5,
        description=(
            "Priority from 1 (highest) to 5 (lowest)."
        ),
    )


class GeminiScoreEvaluation(BaseModel):
    """
    Structured qualitative evaluation generated by Gemini.

    Gemini evaluates resume quality.
    Python remains responsible for deterministic signals
    and final score aggregation.
    """

    # -----------------------------------------------------
    # Content Quality
    # -----------------------------------------------------

    content_quality: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Quality, relevance, specificity, and "
            "usefulness of the resume content."
        ),
    )

    content_quality_rationale: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation for the "
            "content-quality score."
        ),
    )

    # -----------------------------------------------------
    # Skills Presentation
    # -----------------------------------------------------

    skills_presentation: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Quality and clarity of skill presentation."
        ),
    )

    skills_presentation_rationale: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation for the "
            "skills-presentation score."
        ),
    )

    # -----------------------------------------------------
    # Project Evidence
    # -----------------------------------------------------

    project_evidence: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Quality, clarity, specificity, and "
            "evidence contained in project entries."
        ),
    )

    project_evidence_rationale: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation for the "
            "project-evidence score."
        ),
    )

    # -----------------------------------------------------
    # Experience Evidence
    # -----------------------------------------------------

    experience_evidence: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Quality of professional, internship, "
            "research, achievement, or practical evidence."
        ),
    )

    experience_evidence_rationale: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation for the "
            "experience-evidence score."
        ),
    )

    # -----------------------------------------------------
    # Education
    # -----------------------------------------------------

    education_quality: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Quality and clarity of the education "
            "information presented."
        ),
    )

    education_quality_rationale: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation for the "
            "education-quality score."
        ),
    )

    # -----------------------------------------------------
    # Career Direction
    # -----------------------------------------------------

    career_direction: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Clarity and consistency of the stated "
            "career direction."
        ),
    )

    career_direction_rationale: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation for the "
            "career-direction score."
        ),
    )

    # -----------------------------------------------------
    # Professional Clarity
    # -----------------------------------------------------

    professional_clarity: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Clarity, specificity, consistency, and "
            "professional presentation."
        ),
    )

    professional_clarity_rationale: str = Field(
        ...,
        min_length=1,
        description=(
            "Evidence-based explanation for the "
            "professional-clarity score."
        ),
    )

    # -----------------------------------------------------
    # Strengths
    # -----------------------------------------------------

    strengths: list[GeminiScoreStrength] = Field(
        default_factory=list,
        description=(
            "Evidence-based strengths identified "
            "from the resume."
        ),
    )

    # -----------------------------------------------------
    # Improvement Areas
    # -----------------------------------------------------

    improvement_areas: list[
        GeminiScoreImprovement
    ] = Field(
        default_factory=list,
        description=(
            "Evidence-based actionable improvements."
        ),
    )

    # -----------------------------------------------------
    # Evidence
    # -----------------------------------------------------

    evidence: list[str] = Field(
        default_factory=list,
        description=(
            "Short factual observations directly "
            "supported by the resume."
        ),
    )


# =========================================================
# Application-Level Models
# =========================================================
#
# These models are NOT sent to Gemini.
# They are used after Gemini's response is validated.
#
# Strict validation is appropriate here.
# =========================================================


class ScoreDimension(BaseModel):
    """
    Final application-level score dimension.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    score: int = Field(
        ...,
        ge=0,
        le=100,
    )

    weight: int = Field(
        ...,
        ge=0,
        le=100,
    )

    rationale: str = Field(
        ...,
        min_length=1,
    )


class ScoreStrength(BaseModel):
    """
    Final application-level strength.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    category: str = Field(
        ...,
        min_length=1,
    )

    title: str = Field(
        ...,
        min_length=1,
    )

    description: str = Field(
        ...,
        min_length=1,
    )


class ScoreImprovement(BaseModel):
    """
    Final application-level improvement.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    category: str = Field(
        ...,
        min_length=1,
    )

    title: str = Field(
        ...,
        min_length=1,
    )

    description: str = Field(
        ...,
        min_length=1,
    )

    priority: int = Field(
        ...,
        ge=1,
        le=5,
    )


class ResumeScore(BaseModel):
    """
    Final validated Resume Quality Score.

    This is the schema that can later be used for:
    - API responses
    - MongoDB persistence
    - frontend consumption
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    score_version: str = Field(
        ...,
        min_length=1,
    )

    overall_score: int = Field(
        ...,
        ge=0,
        le=100,
    )

    score_label: str = Field(
        ...,
        min_length=1,
    )

    score_breakdown: dict[
        str,
        ScoreDimension,
    ] = Field(
        ...,
        min_length=1,
    )

    strengths: list[
        ScoreStrength
    ] = Field(
        default_factory=list,
    )

    improvement_areas: list[
        ScoreImprovement
    ] = Field(
        default_factory=list,
    )

    scoring_notes: dict[
        str,
        Any,
    ] = Field(
        default_factory=dict,
    )
    