"""
Security Utilities

Purpose:
Handles Google token verification, JWT creation,
and authenticated-user retrieval.
"""

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from google.auth.transport import requests
from google.oauth2 import id_token
from jose import JWTError, jwt

from app.config.settings import settings
from app.services.user_service import UserService


# ---------------------------------------------------------
# HTTP Authentication
# ---------------------------------------------------------

security = HTTPBearer()


# ---------------------------------------------------------
# Google Authentication
# ---------------------------------------------------------

def verify_google_token(token: str) -> dict:
    """
    Verify the Google OAuth ID token.

    The token is generated by Google on the frontend
    and sent to the backend for verification.
    """

    try:
        # -------------------------------------------------
        # Temporary diagnostic information.
        #
        # We inspect claims only.
        # We NEVER print the actual token.
        # -------------------------------------------------

        unverified_claims = jwt.get_unverified_claims(token)

        print("\n===== GOOGLE TOKEN DEBUG =====")
        print("Audience:", unverified_claims.get("aud"))
        print("Issuer:", unverified_claims.get("iss"))
        print("Subject:", unverified_claims.get("sub"))
        print("Email:", unverified_claims.get("email"))
        print("Expiration:", unverified_claims.get("exp"))
        print("==============================\n")

        # -------------------------------------------------
        # Real Google token verification.
        # -------------------------------------------------

        verified_token = id_token.verify_oauth2_token(
            token,
            requests.Request(),
            settings.GOOGLE_CLIENT_ID,
        )

        print("✅ Google ID token verified successfully.")

        return verified_token

    except ValueError as error:
        print("❌ Google ID token verification failed.")
        print("Reason:", error)

        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid Google authentication token.",
        )

    except Exception as error:
        print("❌ Unexpected Google authentication error.")
        print("Reason:", error)

        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Google authentication failed.",
        )


# ---------------------------------------------------------
# JWT Creation
# ---------------------------------------------------------

def create_access_token(data: dict) -> str:
    """
    Create an application JWT access token.

    Args:
        data: Data to store inside the JWT payload.

    Returns:
        Encoded JWT string.
    """

    payload = data.copy()

    return jwt.encode(
        payload,
        settings.JWT_SECRET_KEY,
        algorithm=settings.JWT_ALGORITHM,
    )


# ---------------------------------------------------------
# Current User
# ---------------------------------------------------------

def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
):
    """
    Extract and validate the current user from the
    application JWT.

    This function is used as a FastAPI dependency
    for protected endpoints.
    """

    token = credentials.credentials

    try:
        # Decode and verify JWT.
        payload = jwt.decode(
            token,
            settings.JWT_SECRET_KEY,
            algorithms=[settings.JWT_ALGORITHM],
        )

        # Extract user identity.
        email = payload.get("sub")

        if not email:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid authentication token.",
            )

    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired authentication token.",
        )

    # Find authenticated user.
    user = UserService.find_by_email(email)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="User not found.",
        )

    return user